<template>
   <div>
    <HeroSection/>
    <RiskSection/>
    <HowItWorksSection/>
    <ServicesSection/>
    <TestimonySection/>
    <ContactSection/>
    <MapSection/>
    <BookVerifySection/>
   </div>
</template>